
spring:
  # MariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
    database: mysql

  # redis
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    host: ${REDIS_URL}
    port: ${REDIS_PORT}

  # cache
  cache:
    type: redis
    redis:
      cache-null-values: true

reservation:
  url: ${RESERVATION_URL}
  port: ${RESERVATION_PORT}