
spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ticketaka?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: Yk2469804!

  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  # redis
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: 172.19.171.241

  # cache
  cache:
    type: redis
    redis:
      cache-null-values: true