
spring:
  # MariaDB
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # JPA
  jpa:
    database: mysql  # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # redis
  redis:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    host: ${REDIS_URL}
    port: ${REDIS_PORT}

  # cache
  cache:
    type: redis
    redis:
      cache-null-values: true

reservation:
  url: ${RESERVATION_URL}
  port: ${RESERVATION_PORT}